[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  mrcodetastic/ESP32 HUB75 LED MATRIX PANEL DMA Display@^3.0.14
  tzapu/WiFiManager@^2.0.17
build_flags =
  -DCORE_DEBUG_LEVEL=1
