[platformio]
default_envs = waveshare-panel-test

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
  mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display@^3.0.15
  adafruit/Adafruit GFX Library@^1.12.1
build_flags =
  -DCORE_DEBUG_LEVEL=1

[waveshare-s3]
board = esp32-s3-devkitc-1
board_build.flash_size = 32MB
board_build.flash_mode = dout
board_build.psram_type = opi
board_build.arduino.memory_type = opi_opi
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
board_build.embed_files = data/cert/x509_crt_bundle.bin
board_upload.flash_size = 32MB
board_upload.maximum_size = 6553600
upload_port = /dev/cu.usbmodem*
monitor_port = /dev/cu.usbmodem*
build_flags =
  ${env.build_flags}
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

[env:waveshare-panel-test]
extends = waveshare-s3
build_src_filter = +<panel_test.cpp> -<main.cpp>

[env:waveshare-album-clock]
extends = waveshare-s3
build_src_filter = +<main.cpp> -<panel_test.cpp>
